#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DATABASE_URL="psql://$POSTGRESQL_USER:$POSTGRESQL_PASSWORD@$POSTGRESQL_HOST:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE"

echo 'Trying connect to database.' 

python << END
import sys
import psycopg2

try:
    psycopg2.connect(
        host="${POSTGRESQL_HOST}",
        port="${POSTGRESQL_PORT}",
        dbname="${POSTGRESQL_DATABASE}",
        user="${POSTGRESQL_USER}",
        password="${POSTGRESQL_PASSWORD}"
    )
except psycopg2.OperationalError:
    print('Postgres not available')
    sys.exit(-1)
sys.exit(0)
END

exec "$@"